package com.rocketpartners.game.events

enum class EventType {
    TURN_CONTROLLER_ON,
    TURN_CONTROLLER_OFF,
    GAME_PAUSE,
    GAME_RESUME,
    PLAYER_SPAWN,
    PLAYER_READY,
    PLAYER_JUST_DIED,
    PLAYER_DONE_DYIN,
    GAME_OVER,
    BEGIN_ROOM_TRANS,
    CONTINUE_ROOM_TRANS,
    END_ROOM_TRANS,
    GATE_INIT_OPENING,
    GATE_FINISH_OPENING,
    GATE_INIT_CLOSING,
    GATE_FINISH_CLOSING,
}